version: '3.7'

services:
  #Postgres Database 
  postgres-database: 
    container_name: postgres-database-parking
    image: postgres:12.3
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data" 
    #Enviroment variable for DB name, user and password 
    environment:
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
      POSTGRES_DB: parking
    ports:
      - 5432:5432
    