version: '3.7'

services:

  #Postgres Database 
  postgres-database: 
    container_name: postgres-database-parking
    image: postgres:12.3
    volumes:
      - "/var/lib/postgresql/data:/var/lib/postgresql/data" 
    #Enviroment variable for DB name, user and password 
    environment:
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
      POSTGRES_DB: parking
    ports:
      - 5432:5432
      
  #Prometheus for capture metrics    
  prometheus:
     image: prom/prometheus:latest
     container_name: prometheus
     volumes:
     - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
     command:
     - "--config.file=/etc/prometheus/prometheus.yml"
     ports:
     - 9090:9090  
     
  #Grafana for diplay graphics 
  grafana:
     image: grafana/grafana:latest
     container_name: grafana
     ports:
     - 3000:3000
     
  #jenkins for automatic build
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8083:8080
      - 50003:50000
    networks:
    - sonarnet  
    container_name: my-jenkins-3
    volumes:
      - ~/jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    
  #Sonarqube for test coverage
  sonarQube:
    container_name: sonarqube
    image: sonarqube
    expose:
      - 9000
    ports:
      - "9000:9000"
    networks:
    - sonarnet 
    environment:
      - sonar.jdbc.url=jdbc:postgresql://pg-sonar:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    depends_on:
    - pg-sonar
    volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  #Sonarqube Database responsible to support Sonarqube
  pg-sonar:
    container_name: pg-sonar
    image: postgres
    networks:
    - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    
networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
 # jenkins_home: 
 # jenkins_backup:
  
 